### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by TimCoraxAudio** [BSData/gates-of-antares#152]
I would like to be able to update the data for this repo please

**Comment by TimCoraxAudio** [comment]
Any update on this?

**Comment by amis92** [comment]
Since there is no active maintainer, I'll trust you with this responsibility, then. Please accept the invitation!

Hello, @TimCoraxAudio. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/gates-of-antares/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
