### ISSUE TITLE
C3 v10: No minimum strength Plasma lance squads

### ISSUE THREAD

**Issue by glasvandrare** [BSData/gates-of-antares#48]
I discovered that the only way to have a minimum size Strike Squad and Drop Squad with plasma lance is to reduce the regular troopers by one, and add a Plasma Lance trooper. This generates an error, as you have too few regulars, according to Battle Scribe. 

Is this limitation intentional? I see nothing supporting it in the army list.

**Comment by Vescarea** [comment]
That might be an old file? Try deleting local content or clear cache and try re syncing the data, but had a check on my app and it comes up with this.
![normalappimage 14](https://cloud.githubusercontent.com/assets/11745281/14770182/1251d56c-0a63-11e6-8fe5-d410c2e44fda.png)

so you have the basic 4 strike troopers and their leader with the plasma lance option.
That should be the case.

**Comment by glasvandrare** [comment]
You're right, I forced an update and got it like that. 

However, for the Drop Troopers there is still some kind of bug: 

C3 Drop Squad (181pts) [Plasma Lance (5pts)]
····> Drop Leader [HL Armour (E), Plasma Carbine (E), X-Sling (E)]
····3x Drop Trooper (78pts) [3x HL Armour (E), 3x Plasma Carbine (E), **3x Plasma Lance** (E)](My bolding of text)

And it does not seem to matter if I select the PL upgrade or not, there is still 3 Carbines and 3 Lances.

**Comment by Vescarea** [comment]
I shall get on that asap :)

**Comment by FallenHero143** [comment]
In my v11 of the Concord file I've fixed both these issues.  I changed the Plasma Lance option to keep the plasma lance trooper looking consistent.  The only problem is that Battlescribe won't automatically decrement the current number of troopers when you add a Plasma Lance Trooper, you have to do it manually.

**Comment by Vescarea** [comment]
I know I tried that way before and it didnt work so i reverted it to the original way which was fine. Could you let me know of the changes you made? I polished up the concord and freeborn files so selections more user friendly.

**Comment by Vescarea** [comment]
Not being a critic i just like to se how others arrange stuff.

**Comment by FallenHero143** [comment]
Main changes that I can recall:
1.  Added Army Options to the Concord file, requiring a change in the Game System file (adding a Category type)
2. Added a Strike Trooper Command Trooper to account for the regular troopers have Accuracy 6 instead of the normal 5.
3. Added a new Interceptor unit without command that is limited to 1.
4. Fixed the Plasma Lance duplication error in the Drop Trooper files and allowed them to have up to two as the rules state.
5. Changed the Plasma Lance option to a Plasma Lance Trooper with all that entails.
6. Fixed Plasma Grenades on some units, as it wasn't calculating correctly.

There might have been other small changes, I seem to recall adding copies of some weapons or gear to allow for different costs and selection limits depending on whom they were attached to.

**Comment by Vescarea** [comment]
1. I don't understand this
2. I believe you cant take without command squad
   I checked over the grenades in each unit but cant see a problem.
   example unit
   you get 2pt for strike commander/ Leader
   and extra 2pt for every selection of strike trooper

**Comment by FallenHero143** [comment]
1.  The way it works there is now in the Game System file a new category called Army Options in addition to the Tactical, Support, Strategic and Auxiliary categories that were there previously.  In the Concord file I have added entries for each force size and an entry group with all the army options under each force size.  Many of the options are limited by the number of Auxiliary choices you can have and this was the way I figured out how to make that work.  If you look at it in the Roster Editor it makes far more sense.  It looks a bit confusing in the Catalogue Editor because of the alphanumeric sorting.
2.  The Strike Command Troopers I added replace the regular Strike Troopers in the Strike Trooper Command Squad.  Regular troopers have Acc 5.  In the command squad they have Acc 6 so I added the new profile and entry to account for this.
3.  The Plasma Grenades were probably wrong on the units I added, so that's what I remember fixing.

**Comment by glasvandrare** [comment]
RE: 4, it seems that it is not possible to have less than 3 regular Drop Troopers, even after adding a plasma lance (this is till in FH143s version).

Other than that it looks good.

**Comment by FallenHero143** [comment]
That is the way it should work.  You have a Leader and 4 Troopers as the base squad.  You add a Plasma Lance and now you can go down to 3 Troopers.  The Drop Squad works almost the same, except that you get the first Plasma Lance included and can add a second one.

The Command squads of each (Strike and Drop) have fewer Troopers, but the main squads start with five.

**Comment by FallenHero143** [comment]
RE #4.  You're correct.  There should be a modifier with condition to decrement the minimum selection to 2 from 3.  I fixed it in my file and tested it.  Now, what's the proper way to get it posted?

**Comment by glasvandrare** [comment]
FallenHero: Either push it here (to a separate branch, which we then can merge from), or mail the changed file (although I'd suggest the first solution).

**Comment by clandaith** [comment]
I've already fixed the problem and merged it into master.  It will go out
with the next release.

++++++++++++++++++
Troy Davidson, KF7MTE

**Comment by glasvandrare** [comment]
Great!

**Comment by clandaith** [comment]
Actually, it looks like it's still awaiting to be merged.

**Comment by glasvandrare** [comment]
Strange. Do you have the commit ID?

**Comment by clandaith** [comment]
Here's the pull request.  I screwed up and pushed the change directly to master.  Didn't realize I was on the branch.  I looked up what was the best way to fix the problem and the easiest that was recommended was to just make another change to the file and do a pull request.  So, I then did a minor change by adding the page that the rule was found on.

Here's the request.

https://github.com/BSData/gates-of-antares/pull/64

**Comment by glasvandrare** [comment]
That change seems to only affect Ghar, at least as far as I can see.

**Comment by clandaith** [comment]
Doh!  I'm on the wrong freaking issue thread.  Never mind.  I haven't had enough coffee this morning.

**Comment by glasvandrare** [comment]
Been there, done that (today, even.. although it's afternoon here... )

That means that we don't have a fix for the Plasma issues merged yet, apart from FH143s repo?

**Comment by clandaith** [comment]
That is correct.  The two things, both Ghar related, I fixed last night were:

Battlesuits were listed as a minimum of 1.  Changed this to 0.
Scutters needed to have their plasma amplifiers changed to a maximum of 1.  Originally it was -1 which then allows the user to select it multiple times.  By changing it to 1, this is now a check box like it should be.

**Comment by glasvandrare** [comment]
Aren't battlesuits 1+ though? Page 170 (PDF): **Special:Your force must include at least one Ghar Battle Squad**

**Comment by clandaith** [comment]
SON OF A BISNITCH!  Damnit.  That's already merged into master.  I can create a fix and push it out.

**Comment by clandaith** [comment]
Here's the fix for that:

https://github.com/BSData/gates-of-antares/pull/65
