### ISSUE TITLE
Add Ghar Rebel Outcast Army

### ISSUE THREAD

**Issue by shammond42** [BSData/gates-of-antares#79]
Add the new army and all of the units within.

**Comment by Mayegelt** [comment]
Made one in the last few hours, seems to work, not sure if there are any errors, and kinda need to fill out a load of rules what are linked up.

https://drive.google.com/open?id=0B2WSzVPkudYKWHNHbDk3LXl5STA

Could also use a bit of tidying up probably. Was my first go at it.

Only 2 probs i know of are that of course it doesn't know the force organisation chart thing for how many tacts and stuff it needs. Also it doesn't know how to deal with what are limited choices. Though all Limited choices I think I put a flag on for the "Limited" rule and also made the Leader of each of the units a "Limited" rather than just a "Model"

**Comment by glasvandrare** [comment]
The 'Limited' thing seems to not throw any errors when taking too many, but other than that I've not found any issues.  I've merged and released the file.

**Comment by Mayegelt** [comment]
Yeah, I wasn't sure how to make it throw up errors for "Limited" stuff when I made it. If you know how to fix it, then I will do the work to do it :)
